### ISSUE TITLE
Trying to support mario-deluna/php-glfw

### ISSUE THREAD

**Issue by crazywhalecc** [crazywhalecc/static-php-cli#121]
https://github.com/mario-deluna/php-glfw looks good to me, but there are some compilation issues to be resolved.

**Comment by jingjingxyk** [comment]
libx11 opengl  静态编译可不容易

libx11 依赖一堆库 （从行业资讯上 看到 XWayland 取代 x11 ) 
opengl 直接与显卡绑定。没啥可移植性 

为啥我知道这个，因为我为了编译gd 中（启用libxpm) 库 和 ffmpeg 时遇到过
最近找到了这个： https://github.com/BtbN/FFmpeg-Builds/tree/master/scripts.d/45-x11  （这个似乎有用）

**Comment by jingjingxyk** [comment]
不起用x11 情况下
```shell

 mkdir -p build
 cd build
 cmake .. \
-DCMAKE_INSTALL_PREFIX={$glfw_prefix} \
-DCMAKE_C_STANDARD=11 \
-DCMAKE_POLICY_DEFAULT_CMP0074=NEW \
-DCMAKE_BUILD_TYPE=Release  \
-DBUILD_SHARED_LIBS=OFF  \
-DBUILD_STATIC_LIBS=ON \
-DGLFW_BUILD_EXAMPLES=OFF \
-DGLFW_BUILD_TESTS=OFF \
-DGLFW_BUILD_DOCS=OFF \
-DGLFW_INSTALL=ON  \
-DGLFW_LIBRARY_TYPE=STATIC \
-DCMAKE_DISABLE_FIND_PACKAGE_X11=ON \
-DGLFW_BUILD_X11=OFF \
-DCMAKE_C_FLAGS="-D_POSIX_C_SOURCE=200809L"


cmake --build . --config Release --target install

```

**Comment by crazywhalecc** [comment]
@jingjingxyk 忘记说了，这个只对 macOS 支持，Linux 就太复杂了，正如你所说。

**Comment by mario-deluna** [comment]
I discovered this repo just yesterday and thought, "This is exactly what I've been searching for!" Today, while browsing through the repo and coming across this issue is just brilliant :) 

Is there something I can adjust in the build process of the extension itself to make it more portable? 
Glfw is currently dynamically linked which for sure doesn't help..

**Comment by crazywhalecc** [comment]
@mario-deluna I've successfully statically compiled glfw into a PHP binary locally, and of course, only for mac. I noticed that it uses macOS frameworks such as OpenGL, CoreVideo, etc. These frameworks cannot be statically linked but will exist on almost every mac, so there are not many problems on macOS. I also tested on a brand new macOS Ventura.

But I did run into some issues during compilation, which I'm now solving through the patch process. For example: when I copy pecl-glfw to the `php-src/ext/glfw` directory for inline compilation, some header files under the `vendor` cannot be found. I just copied these into `buildroot/include` directory and it works. Maybe forgot `-I/path/to/vendor`?

For Linux, I really don't know how to make it, because Linux has many kind of desktop environments and it is also impossible to unify the basic libc library (glibc, musl-libc). The most important thing is some parent libraries are too difficult to compile statically. (For example: this related library: openGL)

**Comment by mario-deluna** [comment]
Amazing, MacOS would already be huge.

I'm going to release `v2.1.3` in a second: https://github.com/mario-deluna/php-glfw/pull/16/files
This should fix the missing header files. I used relative paths before, which were evaluated improperly when glfw was compiled inline under `php-src/ext/glfw`.

I've cloned `static-php-cli` locally and have rudimentarily added php-glfw to test if it would compile now, which it does. I didn't add the glfw library itself, which is why the linking step obviously failed. But since you already got the library statically linked, I didn't want to spend too much time reproducing it for myself.

This repo is super impressive, everything is easy and logical to find, and the code is very readable. I had a missing dependency when I switched my computer, and running `bin/spc doctor --auto-fix` just worked. Just brilliant!

> For Linux, I really don't know how to make it, because Linux has many kind of desktop environments and it is also impossible to unify the basic libc library (glibc, musl-libc). The most important thing is some parent libraries are too difficult to compile statically. (For example: this related library: openGL)

Unfortunately, I've never shipped a game on Linux (including cpp ones) yet, so I have no experience on how to handle that. For php-glfw, I've hardcoded x11 for now, but that's surely not the right solution.

**Comment by crazywhalecc** [comment]
@mario-deluna Thanks a lot! I will check it and create a PR.

**Comment by crazywhalecc** [comment]
@mario-deluna Is it right to do this now? I will merge it. #129

**Comment by crazywhalecc** [comment]
@mario-deluna You may be interested in: Today, while I refactoring version v3, I also took the opportunity to test the possibility of building glfw in my Linux environment. 

The good news is that it is portable. We only need to dynamically link glibc and X11 to make it run on all relatively new desktop distributions. Bad news is it also need install x11 libraries on the building machine.

I'm not sure if it's worth it, but it might be an option for those looking to build portable desktop graphics using PHP.

<img width="1426" height="1332" alt="Image" src="https://github.com/user-attachments/assets/856134b8-864d-455f-a0d8-8b0c675fee2d" />

**Comment by henderkes** [comment]
It's already possible in v2 actually! Just define PKG_CONFIG_PATH to the system's library folder and it will link the libraries that exist there against system versions. I did it for gRPC but it worked with X11 too.

**Comment by crazywhalecc** [comment]
> It's already possible in v2 actually! Just define PKG_CONFIG_PATH to the system's library folder and it will link the libraries that exist there against system versions. I did it for gRPC but it worked with X11 too.

Yeah, I integrated into v3 just now. It will be more easy to build on v3.

**Comment by mario-deluna** [comment]
Awesome @crazywhalecc very nice!
