### ISSUE TITLE
Replace custom PHAR build with Box

### ISSUE THREAD

**Issue by stloyd** [crazywhalecc/static-php-cli#162]
Hey,

In the deploy command, I noticed that you're using some custom code to build the phar file, maybe it's worth considering the usage of [Box](https://box-project.github.io/box/) which allows building, managing, and much more (i.e. out of box phar compression support).

WDYT?

**Comment by crazywhalecc** [comment]
It's a good question. 

At first, this packaging code originated from my own chatbot development framework, and the reason why no other packaging tools were introduced is also very simple: it is very simple enough to do so :P

I haven't written Release Actions for deploy and automatically package an independent binary when a new version is released, because I may need to change the extension availability check process #124 .

Of course, for static-php-cli now, it may be considered to support packaging the project into a single file (using micro) in the future. At this time, using an external packaging tool is a good choice. I've also seen the box project mention this: https://github.com/box-project/box/issues/331

**Comment by crazywhalecc** [comment]
I also want to support this feature before the official 2.0 release, at least other people can just download a `./spc`, and don't even need to install PHP to use it.

**Comment by stloyd** [comment]
I have played locally with both static-php & box, building simple PoC for another project without a problem, I was even able to compress easily the Phar file reducing its size by half.

**Comment by stloyd** [comment]
@crazywhalecc Do you have some particular tests/actions that could be done to prove that phar is good? 

I have fast PoC locally (just global `box compile`, no work on command yet), with quite good results so far:
<img width="889" alt="Zrzut ekranu 2023-09-6 o 15 05 29" src="https://github.com/crazywhalecc/static-php-cli/assets/67402/4cecb2bb-190b-42f4-b31b-34dcceecd9f1">

**Comment by crazywhalecc** [comment]
There is currently no test code specifically used to test the validity of its own phar, but you can use the `dev` command to test whether the configuration file can be read correctly. Under normal circumstances, if the help menu can be displayed normally, it is working normally.

Also, I'm not very familiar with how the box is configured, I might need to look into how it works.

**Comment by crazywhalecc** [comment]
Nevermind, I figured it out. 🙌 Next step is to integrate.

**Comment by stloyd** [comment]
Closing in favor of https://github.com/crazywhalecc/static-php-cli/issues/179
