### ISSUE TITLE
Dynamic loading not supported

### ISSUE THREAD

**Issue by odarcan** [crazywhalecc/static-php-cli#204]
When I try to load a .so extension at startup with
**./php -z extension.so**
I get the error
**Failed loading extension.so:  Dynamic loading not supported**

is this disabled?

**Comment by crazywhalecc** [comment]
Yes, it's disabled. Currently it is not possible to dynamically load libraries on Linux systems. Because the current compilation mode is pure static compilation mode, and under pure static compilation of Linux system, there is no dynamic library linked, and these external extensions cannot be dynamically loaded.

You can load a `.so` extension on macOS, because macOS platform does not support pure static library, almost all binaries need to link `libSystem.dylib` and `libnetwork.dylib`. So if we add `libffi` for `static-php-cli`, we can use `xxx.so` on macOS.

**Comment by odarcan** [comment]
I am experimenting with glfw now and I realized it was compiled as an .so extension.

I thought maybe I could add it on startup.

**Comment by odarcan** [comment]
on mac it says this, just so you know

PHP Warning:  Module "glfw" is already loaded in Unknown on line 0
Warning: Module "glfw" is already loaded in Unknown on line 0

**Comment by crazywhalecc** [comment]
For macOS, we have supported glfw extension. Just compile it `bin/spc build glfw --build-cli`. 

For other extensions, I recommend that you first compile a purely statically compiled PHP, and then use `phpize && ./configure && make && make install` to find `xxxx.so` and use it as an independent `php -d extension=xxxx.so` binary .

**Comment by odarcan** [comment]
Im using both mac and linux now 
I meant the errors occur when I downloaded php 8.2.8 cli for mac here https://dl.zhamao.xin/static-php-cli/

so I didnt compile it.


On linux, I have the glfw.so extension so I asked about loading it at startup.
I understand you are statically loading extensions, but I dont understand why that prevents you from allowing dynamically loading additional extensions.

**Comment by crazywhalecc** [comment]
> I understand you are statically loading extensions, but I dont understand why that prevents you from allowing dynamically loading additional extensions.

In the Linux operating system, purely static files cannot load and use dynamic libraries, and PHP's `.so` extension is also a type of dynamic library. This is due to limitations of **the Linux itself**, not PHP or other reasons. If and only if dynamic compilation is used when compiling PHP, and the ffi extension is enabled, we can use the `extension=xxx.so` method to dynamically load external extensions.

**Comment by crazywhalecc** [comment]
> I meant the errors occur when I downloaded php 8.2.8 cli for mac here https://dl.zhamao.xin/static-php-cli/

The php binary hosted on my server is just a demo, including common extensions, but does not include the ffi extension.

**Comment by DubbleClick** [comment]
If you want to use dynamic extension loading, why are you using *static*-php-cli? I think you just want to either download pre-built binaries for your distro, or compile php dynamically. Compiling php dynamically is fairly straight forward with most extensions, you can follow the official documentation.

**Comment by odarcan** [comment]
A guy made a flatpak of the php, it is now portable with glfw !

@DubbleClick The main problem was to make it portable with glfw.

**Comment by odarcan** [comment]
It works with flatpak, my php game is included with php and works with opengl.
