### ISSUE TITLE
Proper testing with Github actions.

### ISSUE THREAD

**Issue by DubbleClick** [crazywhalecc/static-php-cli#218]
Currently it's really hard to see what combinations of extensions and libraries work together and which ones need looking at. Maybe we can create a few gh actions to automatically test various combinations of extensions and libraries that interact with each other?

Examples are ldap + postgresql (doesn't compile on master) or imagick with libwebp (also doesn't compile on master). Imap in the pr still needs a manual input to compile without openssl.

There are a lot of combinations that influence what works and what doesn't work and we also have 4 different operating systems to check everything on (mac, alpine, debian, redhat).

**Comment by crazywhalecc** [comment]
Yes, this is a missing process. I will currently only test the new extensions and the default extensions included on `dl.static-php.dev/static-php-cli/common/` on different platforms. Do you have any good ideas about this?

I had previously thought about adding a new command, `spc dev:generate-matrix curl`, to generate commands corresponding to multiple combinations of extensions, libraries, one per line, and then run it in no-output mode. But since compilation is time-consuming, and I can't simulate multiple environments locally, running tests in Actions every time I update the code is also redundant.

**Comment by DubbleClick** [comment]
Unfortunately actions is the best idea I have. It will be a time consuming process, there are no two ways about it. Even with a latest gen cpu and an abundance of ram, we'd be looking at at least an hour of runtime locally to do proper tests. Github actions have the advantage of running fully in parallel and on different operating systems.

**Comment by crazywhalecc** [comment]
If you want to use Actions to prevent running tests every time you submit, wouldn't `workflow_dispatch` be better? Just click it when you need to test it, and then make a large matrix.

**Comment by DubbleClick** [comment]
I'm not familiar with it, but anything works as long as it runs in parallel and preferably on cloud hardware. A lot of php developers have little need for 16+ cpu cores, running tests lically would take many many hours for them.

**Comment by DubbleClick** [comment]
Oh, when GitHub actions is limited to 20 parallel jobs, we have something to figure out. The problem is that we cannot easily reuse all libraries because they change depending on what other libraries are active. The only ones we could execute once and then copy over are musl-gcc and musl-cross-compile.

Or maybe we should limit extensive testing to one OS for now. Alpine looks like the best candidate for that because of how lightweight it is and because we don't need to compile musl. Other operating systems could use the binaries generated on Alpine, after all.

**Comment by DubbleClick** [comment]
How about this: one action per OS/arch that builds *all* extensions and libraries (introduce build --all command) = 8 runs.

12 runs on alpine x86 to test combinations.

**Comment by crazywhalecc** [comment]
> How about this: one action per OS/arch that builds all extensions and libraries (introduce build --all command) = 8 runs.

Obviously not. Because some extensions are conflicting. For example, the swow and swoole extensions cannot be compiled at the same time. And even if all extensions and libraries are included, if there is a problem in one or two libraries, it will take a very long time to debug.

I mentioned `workflow_dispatch` (manually triggering workflow) before, and I am actually thinking about making this idea also support arm64 Linux and macOS. Because I can manually start my own Arm virtual machine at home for testing before manual testing (the build is very fast, basically within 5 minutes).

**Comment by DubbleClick** [comment]
Good point.

Then maybe common extensions on each OS, basically just add a few to the ones you already test (pgsql, ldap and imap) and the image libraries. And the rest on Alpine.

**Comment by crazywhalecc** [comment]
I think this extension test does not need to be activated every time a commit is made. Maybe we can write an Actions to test, but when to activate it is a problem :(

**Comment by DubbleClick** [comment]
You can configure github actions to only run on PR's.

**Comment by crazywhalecc** [comment]
> You can configure github actions to only run on PR's.

Yes, it refers to the commit in PR. Sometimes you encounter relatively frequent commits, and some of them have nothing to do with the build. Is there a way to determine which extensions and libraries to test based on this modification before the workflow is run?

**Comment by DubbleClick** [comment]
Not as far as I know, but I don't think we need to? They will run for a long time anyway, but that's fine since public repositories get unlimited minutes.

**Comment by crazywhalecc** [comment]
Currently we tested most of extensions. See [bulk](https://github.com/static-php/static-php-cli-hosted/blob/master/.github/workflows/build-php-bulk.yml).
