### ISSUE TITLE
call php in exec 

### ISSUE THREAD

**Issue by bnnoor** [crazywhalecc/static-php-cli#319]
Hello and thank you for the valuable product you produced :)

I decide to start a file server inside and access the internal server. But this cannot be done.

server.php

`<?php 
exce("php -S localhost:10000");
`

Considering that it is not installed php on the target system, it displays an error. Please tell me how I can first run a server to display information graphically?

**Comment by bnnoor** [comment]
`cat micro.sfx server.php > single`

**Comment by crazywhalecc** [comment]
If you are using microsfx and package PHP and PHP code in one file, you cannot use the built-in PHP web server. The PHP built-in server is only supported with `cli` mode and `micro` is not CLI. (Micro is indeed launched from the command line, but it is still different from the official `cli` SAPI).

If you want to use a built-in web server, it's best to use standalone `php-cli` instead of standalone `micro`.

**Comment by bnnoor** [comment]
thanks jerry, but how can i use them and protect code source ?  need copy php-cli.exe along side compiled micro.sfx ? and how in server.php call the php.exe ?

**Comment by crazywhalecc** [comment]
https://static-php.dev/en/faq/#can-i-protect-my-source-code-with-micro

`micro.sfx` has never been able to protect code. The static-php-cli and phpmicro projects do not involve any functionality for protecting, obfuscating, or encrypting code.
