### ISSUE TITLE
Overwrite .env file on compiled application

### ISSUE THREAD

**Issue by antonkomarev** [crazywhalecc/static-php-cli#334]
Is there is a way to point application to use another .env file instead of bundled one?

**Comment by crazywhalecc** [comment]
I don't quite understand what you are referring to. If you are talking about the configuration file of `spc` (such as `config/ext.json`, etc.), just overwrite it directly in the same directory as `spc`.

**Comment by antonkomarev** [comment]
I mean after compiling code to the executable file, I want to be able to run it with an external .env file.

**Comment by crazywhalecc** [comment]
Sorry, I still don't understand what you mean by `.env`. static-php-cli is just a tool for statically compiling PHP. If you access it from other projects (such as FrankenPHP, Herd or NativePHP), `.env` may be related to these projects.

But according to your description, it may be the packaging source code function of FrankenPHP. You can submit an Issue or PR to the corresponding framework or project: fix the `.env` primary and secondary search directories in the packaging state. (Because the relative path and working directory in the packaging state may be different)
