### ISSUE TITLE
PTY detection issues.

### ISSUE THREAD

**Issue by lyrixx** [crazywhalecc/static-php-cli#335]
Hello, 

Thanks for your hard work! This is really cool.

We are integrating it to [castor](https://github.com/jolicode/castor/pull/260) and be able to ship task runners as standalone lib.

But we face a strange bug with PTY:

With the static binary:

```php
proc_open('echo 1 >/dev/null', [['pty'], ['pty'], ['pty']], $pipes)
```

```
Warning: proc_open(): PTY (pseudoterminal) not supported on this system  
```

Actually, my term DO supports PTY.

```
>…om/jolicode/castor(add-compile-command *%) php -a
Interactive shell

php > var_dump(proc_open('echo 1 >/dev/null', [['pty'], ['pty'], ['pty']], $pipes));
resource(7) of type (process)
```

**Comment by crazywhalecc** [comment]
Thanks for reporting this bug. 

I just looked for the source code and found that this line of patch code was added when the event extension was added ten months ago. https://github.com/crazywhalecc/static-php-cli/blob/cac3ffc7d7fb34bc05603571d2c2da099efeed6b/src/SPC/store/SourcePatcher.php#L214

This issue is related to event extension support on macOS: it will encounter openpty errors when compiling event extensions on macOS.

After removing this line, openpty just works. I will fix this after my vacation.

**Comment by crazywhalecc** [comment]
```
Warning: proc_open(): PTY (pseudoterminal) not supported on this system  
```

The problem with PTY not being supported has been fixed, but I'm not 100% sure that solved your problem. I've merged the code into the main branch, you can test it with `spc` binary (nightly build) or test it with `git clone`.
